# Generated by Django 4.1.6 on 2023-04-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='desc',
        ),
    ]
